Explosion = {   
    [0] =  { NAME = "Grenade",              Log = true,  Punishment = "Ban"  },
    [1] =  { NAME = "GrenadeLauncher",      Log = true,  Punishment = "Ban"  },
    [2] =  { NAME = "Stick Bomb",           Log = true,  Punishment = "Ban"  },
    [3] =  { NAME = "Molotov",              Log = true,  Punishment = "Kick"  },
    [4] =  { NAME = "Rocket",               Log = true,  Punishment = "Ban"  },
    [5] =  { NAME = "TankShell",            Log = true,  Punishment = "Ban"  },
    [6] =  { NAME = "Hi_Octane",            Log = false, Punishment = "Kick"  },
    [7] =  { NAME = "Plance",               Log = false, Punishment = "Ban"  },
    [8] =  { NAME = "PetrolPump",           Log = false, Punishment = "Kick"  },
    [9] = { NAME = "Dir_Steam",            Log = false, Punishment = "Ban"  },
    [10] = { NAME = "Dir_Flame",            Log = false, Punishment = "Ban"  },
    [11] = { NAME = "Dir_Water_Hydrant",    Log = false, Punishment = "Ban"  },
    [12] = { NAME = "Dir_Gas_Canister",     Log = false, Punishment = "Kick"  },
    [13] = { NAME = "Boat",                 Log = false, Punishment = "Ban"  },
    [14] = { NAME = "Ship_Destroy",         Log = false, Punishment = "Ban"  },
    [15] = { NAME = "Truck",                Log = false, Punishment = "Ban"  },
    [16] = { NAME = "Bullet",               Log = true,  Punishment = "Ban"  },
    [17] = { NAME = "SmokeGrenadeLauncher", Log = true,  Punishment = "Ban"  },
    [18] = { NAME = "SmokeGrenade",         Log = false, Punishment = "Ban"  },
    [19] = { NAME = "BZGAS",                Log = false, Punishment = "Ban"  },
    [20] = { NAME = "Flare",                Log = false, Punishment = "Ban"  },
    [21] = { NAME = "Gas_Canister",         Log = false, Punishment = "Ban"  },
    [22] = { NAME = "Extinguisher",         Log = false, Punishment = "Ban"  },
    [23] = { NAME = "Programmablear",       Log = false, Punishment = "Ban"  },
    [24] = { NAME = "Train",                Log = false, Punishment = "Ban"  },
    [25] = { NAME = "Barrel",               Log = false, Punishment = "Ban"  },
    [26] = { NAME = "PROPANE",              Log = false, Punishment = "Kick"  },
    [27] = { NAME = "Blimp",                Log = false, Punishment = "Ban"  },
    [28] = { NAME = "Dir_Flame_Explode",    Log = false, Punishment = "Kick"  },
    [29] = { NAME = "Tanker",               Log = false, Punishment = "Kick"  },
    [30] = { NAME = "PlaneRocket",          Log = true,  Punishment = "Ban"  },
    [31] = { NAME = "VehicleBullet",        Log = false, Punishment = "Ban"  },
    [32] = { NAME = "Gas_Tank",             Log = true,  Punishment = "Kick" },
    [33] = { NAME = "FireWork",             Log = false, Punishment = "Ban"  },
    [34] = { NAME = "Valkyrie_Cannon",      Log = true,  Punishment = "Ban"  }
}